### ISSUE TITLE
HmmGen ignores ncRNA genes

### ISSUE THREAD

**Issue by nikolaichik** [nikolaichik/SigmoID#10]
when picking up locus_tag and gene name from the following gene, HmmGen ignores sRNA genes and picks up names from protein coding genes. For example, there's a GalR site in front of the rsmB ncRNA, but HmmGen picks the names from the following aepA locus, which is incorrect.

**Comment by faultby** [comment]
This should be fixed since HmmGen 2.8

**Comment by nikolaichik** [comment]
works properly now
