### ISSUE TITLE
There was a problem in the following method: deNovoWin:RunButton

### ISSUE THREAD

**Issue by roman-nareiko** [nikolaichik/SigmoID#12]
Во время выполнения операции Searching Uniprot Reference Proteins вылетает ошибка. Существует ли логирование ошибок? 
![screenshot from 2017-05-03 17-21-03](https://cloud.githubusercontent.com/assets/24397605/25664989/f6ea64e0-3024-11e7-969c-98469893c8b8.png)

**Comment by nikolaichik** [comment]
Нормального лога нет (кроме той информации, что видна в скриншоте). Ошибка одноразовая или перманентная?

**Comment by roman-nareiko** [comment]
Перманентная. Может быть, с настройками не всё в порядке?
![screenshot from 2017-05-03 18-31-32](https://cloud.githubusercontent.com/assets/24397605/25668345/18a80970-302f-11e7-8d47-f196495acdcb.png)

**Comment by roman-nareiko** [comment]
Всё-таки программа отработала 1 раз без ошибок, но в папке с результатами только 3 файла:
CDS.fasta
hmmsearch_result_withCRtags.txt
Search.log

Когда же выполнение заканчивается неудачей, в папке с результатами создаются ещё папки, например, meme_results

Вот скриншот с результатами:
![screenshot from 2017-05-03 19-31-49](https://cloud.githubusercontent.com/assets/24397605/25671005/32f33cf2-3037-11e7-84a7-d5ba93ec2fc2.png)

**Comment by nikolaichik** [comment]
Скорее всего проблема с двоеточием в protein_id. Попробуйте во всем .gbk файле просто убрать четыре лишние буквы "BSU:" (через замену по всему тексту в текстовом редакторе)

**Comment by roman-nareiko** [comment]
Большое Вам спасибо. Заработало.

**Comment by nikolaichik** [comment]
The problem is actually caused by incorrect GenBank file, so closing the issue
