### ISSUE TITLE
There was a problem in the following method: SeqRetrieval:GetRegSeq

### ISSUE THREAD

**Issue by raman-nareika** [nikolaichik/SigmoID#13]
Во время выполнения возникла ошибка. Но после закрытия модального окна выполнение продолжилось.

![screenshot from 2017-05-04 00-33-06](https://cloud.githubusercontent.com/assets/24397605/25682762/fd443676-3061-11e7-87fe-045c29db0809.png)

**Comment by nikolaichik** [comment]
Эта ошибка проскакивает время от времени на убунте, причину понять не могу. Скорее всего проблема среды разработки. Бывает редко, почти ни на что на влияет

**Comment by nikolaichik** [comment]
Seems to be fixed now
