### ISSUE TITLE
Length threshold

### ISSUE THREAD

**Issue by faultby** [nikolaichik/SigmoID#2]
At the moment HmmGen.py calculates an upper boundary of feature's length using the "envfrom" - "env to" columns from hmmer's report, which, I think,  doesn't work correctly.That is how we are trying to avoid those different in length between alignment and the hit regions in genome because the distance between binding sites is essential. 
And the question is will it be better to use comparing the differences  between "hmmfrom"-"hmmto" and "alifrom"-"ali to" to prevent problems with distances? If the differences between them are equal or +-1, then HmmGen leaves it. The upper boundary will be used to set up the length of annotated features in Genbank file.

**Comment by nikolaichik** [comment]
Using "envfrom" - "env to" seems to me as the best option, as hmmer sometimes shows shorter aligments than necessary. I also don't see errors in hmmer reports here. I still think we have a parsing problem. In this example "envfrom" - "env to" = 18, but hmmgen with - L=15:18 removes this hit
    hmmfrom    hmmto     alifrom    alito      envfrom    envto
    1    15            1801560         1801546            1801564   1801546

**Comment by faultby** [comment]
The equation "env to" - "envfrom" gives us not full length, as it doesn't include the first letter, which is "envfrom". The correct one is  "env to" -  ("envfrom" - 1).

For example:
envfrom = 1
env to = 3
env to - envfrom = 3 - 1 = 2 (but the length is 3, as it contains 1, 2 and 3)
env to - (envfrom - 1) = 3 - (1 - 1) = 3 (which is correct to calculate length)

So that's why those two hits for the PhoP were not annotated by HmmGen: their both lengths (19 b.p. by the calculations) were over the treshold, which was 18 b.p.

**Comment by faultby** [comment]
Of course, if the strand is "-" the equation transforms to:
envfrom - (env to - 1) = length

**Comment by nikolaichik** [comment]
An obvious thing, but you can't expect much from a brain after a whole day of a very stupid paperwork :)
So, no bugs here and I still feel using envelopes would give better results, we just need to remember that the envelope could be longer than the profile and use the -L switch accordingly. 

So, no need to change the script here!

**Comment by nikolaichik** [comment]
Well, after running several checks with different profiles using "envfrom" - "env to" seems to create more problems than it was supposed to solve. So we're probably better off with your original proposal to use "alifrom"-"ali to"

**Comment by faultby** [comment]
I have just updated the HmmGen.py, where was used "alifrom"-"ali to" way to check correctness of distances. Should work correctly, but more carefull testing  is needed.

**Comment by nikolaichik** [comment]
Seems to work properly as of version 2.1
