### ISSUE TITLE
TermGen: correct coordinates

### ISSUE THREAD

**Issue by nikolaichik** [nikolaichik/SigmoID#5]
U-tails should be taken into account when adding terminator coordinates to the annotation

**Comment by faultby** [comment]
U-tails are now (TermGen 1.4) added to the terminators.

**Comment by nikolaichik** [comment]
Only some tails are included! Check, for example, terminators after OA04_01460 and OA04_01490

**Comment by nikolaichik** [comment]
Works as expected
