### ISSUE TITLE
TermGen: annotation improvement

### ISSUE THREAD

**Issue by nikolaichik** [nikolaichik/SigmoID#6]
1. The "terminator" feature has been replaced by NCBI. Annotation should comply with the current GenBank format (that unfortunate "regulatory" thing).
2. The [ gene="UNK" ] qualifiers are currently added to terminators after loci without gene names. These are hardly useful and should be dropped

**Comment by faultby** [comment]
Adjustment has been done. Should work properly since TermGen 1.4 version.

**Comment by nikolaichik** [comment]
Works as expected

**Comment by nikolaichik** [comment]
gene="UNK" still slips through. Example: terminator after OA04_01490

**Comment by nikolaichik** [comment]
Actually, verything is fine –opened (by mistake) a file already annotated with previous version of TermGen
